### ISSUE TITLE
Sprinting + Jumping ~8 blocks on new blocks

### ISSUE THREAD

**Issue by CaptainObvious0** [CaptainObvious0/NoCheatPlus#11]
As title says, it seems jumping + sprinting over trap doors flags for hspeed and lowjump after about 8 blocks. Issue only happens when the trap door is down. Issue does not occur any other time.

**Comment by CaptainObvious0** [comment]
Seems the issue is not only with trap doors, but any other block with different block margins. Only happens when sprinting + jumping, for more than 8 blocks

**Comment by CaptainObvious0** [comment]
Fixed with 16b32cb

**Comment by PhanaticD** [comment]
just compiled and set up the latest version as of right now and its still happening for players, on one high dark oak slab

**Comment by CaptainObvious0** [comment]
Make sure that the block has the flag ground_height, or else it won't apply the workaround. 

If the block already does, please post a debug log: https://github.com/NoCheatPlus/Docs/wiki/Debugging#on-the-fly-debug-output-for-individual-players

**Comment by PhanaticD** [comment]
I am using markelf's config I have DARK_OAK_SLAB: default+ground+xz100+ground_height+allow_lowjump+ign_passable

/ncp debug doesnt seem to be a valid command just gives me the help text

**Comment by CaptainObvious0** [comment]
Improper command arguments will return the help message. 

Go to NoCheatPlus/nocheatplus.log and clear it before you start anything. Do `/ncp debug player (player)` and reproduce the issue until you are flagged. Go back to the nocheatplus.log file and post it here.

**Comment by CaptainObvious0** [comment]
@PhanaticD Upon further investigation, it seems that if the block has the 'allow_lowjump' flag it does not apply the workaround. I'll fix this with the next version.
